### ISSUE TITLE
Water Constructor

### ISSUE THREAD

**Issue by JAVIERSIG** [Jannik-Schilling/WaterNetAnalyzer#2]
Hi; one question please,,,
In section one, Water network builder, I have no choice but to choose the layer from which to build the network,
It is like that, or I have to do something apart.
Thank you

**Comment by Jannik-Schilling** [comment]
Yes, you´re right. You have to choose the line layer which will be the water network. The tool will add informations about connections in the water network.
The description in the gui might be confusing here. I´ll change that in future versions.

Maybe the description [here](https://github.com/Jannik-Schilling/WaterNetAnalyzer) can help you.
