### ISSUE TITLE
TypeError: tr() missing 1 required positional argument: 'string'

### ISSUE THREAD

**Issue by AlisterH** [Jannik-Schilling/WaterNetAnalyzer#4]
I'm not sure if the offending code actually affects usage of the plugin, but this plugin causes the QGIS locator bar to output a python error:
````
2020-10-21T13:52:23     WARNING    Traceback (most recent call last):
              File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python/plugins\processing\gui\AlgorithmLocatorFilter.py", line 90, in fetchResults
              tags = [*a.tags(), a.provider().name(), a.group()]
              File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\WaterNetAnalyzer-master\Water_Netw_Constructor.py", line 360, in group
              return self.tr()
             TypeError: tr() missing 1 required positional argument: 'string'

**Comment by Jannik-Schilling** [comment]
hey, thats right... I didn´t get this warning so far. But there was indeed something missing and I hope i fixed it in the new version. I just uploaded the new version here (1.6)  so you can install it via zip. It should be available in the plugin repository in some hours.

**Comment by Jannik-Schilling** [comment]
> hey, thats right... I didn´t get this warning so far. But there was indeed something missing and I hope i fixed it in the new version. I just uploaded the new version here (1.6) so you can install it via zip. It should be available in the plugin repository in some hours.

Version 1.6 is now approved in the QGIS plugin reposity. Do you still get the error message?
