### ISSUE TITLE
TypeError: setEnabled(self, bool): argument 1 has unexpected type 'Flags'

### ISSUE THREAD

**Issue by rarygit** [Jannik-Schilling/WaterNetAnalyzer#7]
QGIS version | 3.18.3-Zürich | QGIS code branch | Release 3.18
OS Version | Ubuntu 20.04.4 LTS
Plugin: WaterNetAnalyzer v1.7

Plugin installed OK.

While using Water Net Analyzer plugin & the test data, attempting the first step "1. Water Network Constructor", it reported a python error which I do not understand; how should I interpret this and what is the solution? Thanks for any help.

2022-08-19T16:27:02     WARNING    Traceback (most recent call last):
              File "/media/..../conda_envs/envs/qgis3/share/qgis/python/plugins/processing/gui/AlgorithmDialog.py", line 194, in runAlgorithm
              self.cancelButton().setEnabled(self.algorithm().flags() & QgsProcessingAlgorithm.FlagCanCancel)
             TypeError: setEnabled(self, bool): argument 1 has unexpected type 'Flags'

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    AlgorithmDialog.py
    ---------------------
    Date                 : August 2012
    Copyright            : (C) 2012 by Victor Olaya
    Email                : volayaf at gmail dot com

Lines 180 to 194, AlgorithmDialog.py:

                self.cancelButton().setEnabled(self.algorithm().flags() & QgsProcessingAlgorithm.FlagCanCancel)
                if executeIterating(self.algorithm(), parameters, self.iterateParam, self.context, self.feedback):
                    self.feedback.pushInfo(
                        self.tr('Execution completed in {0:0.2f} seconds').format(time.time() - start_time))
                    self.cancelButton().setEnabled(False)
                    self.finish(True, parameters, self.context, self.feedback)
                else:
                    self.cancelButton().setEnabled(False)
                    self.resetGui()
            else:
                command = self.algorithm().asPythonCommand(parameters, self.context)
                if command:
                    ProcessingLog.addToLog(command)
                QgsGui.instance().processingRecentAlgorithmLog().push(self.algorithm().id())
                self.cancelButton().setEnabled(self.algorithm().flags() & QgsProcessingAlgorithm.FlagCanCancel)

########################################################################################

@Jannik-Schilling  Correct diagnosis re. conda, and thanks for the link!
WaterNetAnalyzer and generate-swmm-inp both work on Windows 10 qgis installation, using osgeo4w.

This is the first time I have had a problem with conda and a qgis plugin on ubuntu 20.04.

**Comment by Jannik-Schilling** [comment]
This is not directly related to the plufgin. It seems to be a problem with QGIS running in a conda environment. See:
https://github.com/qgis/QGIS/issues/47966
